name: Build and Upload

on:
  push:
    branches:
      - test
      - main
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
        name: ${{ github.ref_name }}
    steps:
      - name: Echo environment
        run: echo ${{ github.ref_name }}
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Npm install
        run: npm install
        
      - name: Build
        run: npm run build -- -- --mode ${{ github.ref_name }}
        
      - name: Upload build dir
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
  deploy:
    needs: [build]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
        name: ${{ github.ref_name }}
    steps:
      - name: Echo environment
        run: echo ${{ github.ref_name }}
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Npm install
        run: npm install
        
      - name: Build
        run: npm run build -- -- --mode ${{ github.ref_name }}
        
      - name: Upload build dir
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
