name: Deploy

on:
  workflow_dispatch:   

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
        name: ${{ github.ref_name }}
    steps:
      - name: Download build artifact via API
        id: download-artifact
        uses: actions/github-script@v6
        with:
            script: |
              const { data: artifacts } = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.run_id
              });
              const artifact = artifacts.find(a => a.name === 'build-artifact-${{github.ref_name}}');
              if (!artifact) {
                throw new Error('Artifact not found');
              }
              return artifact.archive_download_url;

      - name: Download artifact file
        run: |
          curl -L ${{ steps.download-artifact.outputs.result }} -o artifact.zip
          unzip artifact.zip -d dist

      # - name: Download build dir
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build-artifact
      #     path: dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Sync to S3
        run: aws s3 sync dist s3://${{ secrets.S3_BUCKET }}

      - name: Invalidate cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
