name: Deploy

on:
  workflow_dispatch:   

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
        name: ${{ github.ref_name }}
    steps:
      - name: Download build dir
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Sync to S3
        run: aws s3 sync dist s3://${{ secrets.S3_BUCKET }}

      - name: Invalidate cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
